# Generated by Django 4.1.2 on 2022-11-16 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 16, 13, 22, 38, 636574, tzinfo=datetime.timezone.utc)),
        ),
    ]
